policy:
  - template: [userstoriesgeneral.yml]
    section:
      - id: [story_topic]
        block-list: [other]
        label:
          - name: bug
            keys: ['bug']

          - name: documentation
            keys: ['documentation']

          - name: duplicate
            keys: ['duplicate']
