policy:
  - section:
      - id: [story_topic]
        block-list: ['None', 'Other']
        label:
          - name: 'bug'
            keys: ['bug']
          - name: 'documentation'
            keys: ['documentation']
          - name: 'duplicate'
            keys: ['duplicate']
   
