policy:
  - section:
      - id: [topic]
        label:
          - name: 'bug'
            keys: ['bug']
          - name: 'documentation'
            keys: ['documentation']
          - name: 'duplicate'
            keys: ['duplicate']
   
