blank_issues_enabled: false
contact_links:
  - name: Mukurtu Support
    url: https://support.mukurtu.org
    about: These forms are for feature requests and technical bug reports. If you need support, please review our documentation and contact the support team here.