name: Hubs-only Mukurtu CMS user story
description: Use this form if you are part of the Mukurtu Hubs and Spokes, or if otherwise requested by the Mukurtu development team.
title: Provide a short descriptive title for your user story
labels: ["user story"]
body:
  - type: checkboxes
    id: story_type
    attributes:
      label: Type of user story
      description: Select the type of user story.
      options:
        - label: New feature or tool
        - label: Update to an existing feature or tool
        - label: Other (please specify below)
    validations:
      required: true

  - type: input
    id: story_type_other
    attributes: 
      label: Other user story type
      description: If you selected "Other", please briefly describe your story type.
    validations:
      required: false

  - type: dropdown
    id: story_topic
    attributes:
      label: Topic
      multiple: true
      description: From the [Mukurtu User Manual](https://mukurtu-user-manual.readthedocs.io/). Can select multiple topics. Specify other if existing topics do not apply.
      options:
        - bug
        - categories
        - collections
        - comments
        - communities
        - cultural protocols
        - customization
        - dictionary
        - digital heritage
        - integrations
        - local contexts
        - localization
        - mapping and leaflet
        - media
        - migration
        - notifications and events
        - person records
        - publishing workflows
        - roundtrip
        - search and discovery
        - site configuration and administration
        - taxonomies
        - theme/look and feel
        - user management
        - other
    validations:
      required: true

  - type: input
    id: story_topic_other
    attributes: 
      label: Other topic
      description: If you selected "Other topics", please briefly describe your story topic.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |

        __User story format__
        Our user stories follow the *As a...*, *I want to...*, *So that...* format.
        eg: *As a* community manager, *I want to* create new user accounts, *so that* I don't have to ask the site administrator to do it.
        
  - type: dropdown
    id: user_type
    attributes:
      label: In this user role
      multiple: true
      description: Select each user type that this applies to. Can select multiple user types. 
      options:
        - Mukurtu administrator
        - Community manager
        - Community affiliate
        - Protocol steward
        - Protocol member
        - Protocol affiliate
        - Contributor
        - Community record steward
        - Curator
        - Language steward
        - Lanugage contributor
        - Authenticated user
        - Visitor
    validations:
      required: true

  - type: input
    id: Action
    attributes:
      label: I want to perform this action
      description: Please describe the action you would like to take in this role.
    validations:
      required: true

  - type: input
    id: Benefit
    attributes:
      label: So that this benefit will occur. 
      description: Please describe the benefit that taking this action would confer.
    validations:
      required: true

  - type: input
    id: Acceptance_criteria
    attributes:
      label: Acceptance criteria
      description: A list of items or descriptions of what success looks like for the action or feature described. For a list, please number or bullet your points.
    validations:
      required: true
      
  - type: textarea
    id: screenshots
    attributes:
      label: Example screenshots
      description: Optionally attach screenshots here.
      placeholder: If you have an example of something similar from elsewhere, you can add screenshots here.
      
  - type: checkboxes
    id: Submitting_org
    attributes:
      label: Submitting organization/hub
      description: If you are not a member of the Mukurtu Hubs project, please select "Other organization", and identify your institution, organization, or community.
      options:
        - label: Alaska Hub
        - label: California Hub
        - label: Hawaii and Pacific Hub
        - label: New South Wales, Australia Hub    
        - label: US East Hub        
        - label: US Midwest Hub
        - label: US West Hub
        - label: Other organization
    validations:
      required: true

  - type: input
    id: submitting_org_other
    attributes: 
      label: Other organization
      description: If you selected "Other organization", please identify your institution, organization, or community.
    validations:
      required: false
      
  - type: checkboxes
    id: origin_user_story
    attributes:
      label: Origination of user story
      description: If you are not a member of the Mukurtu Hubs project, please skip this question.
      options:
        - label: Requested by Mukurtu Hubs staff
        - label: Requested by Mukurtu Hubs community partner
        - label: Other origin
    validations:
      required: false

  - type: input
    id: origin_other
    attributes: 
      label: Other origin
      description: If you selected "Other origin", please identify the origin of your request.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Support Tools: 
        - [Mukurtu 4 User Manual](https://mukurtu-user-manual.readthedocs.io/)
