name: General Mukurtu CMS user story
description: Use this form if you are submitting an issue as a general Mukurtu user.
title: Mukurtu CMS User Stories Submission - General Users 
labels: "user story"
body:
  - type: checkboxes
    id: story_type
    attributes:
      label: Type of user story
      description: Select the type of user story.
      options:
        - label: New feature/tool
        - label: Update to existing feature/tool
        - label: Other
    validations:
       required: true

  - type: input
    id: story_type_other
    attributes: 
      label: Other
      description: If you selected "Other", please briefly describe your story type.
    validations:
      required: false

  - type: dropdown
    id: story_topic
    attributes:
      label: Topic of user story
      multiple: true
      options:
        - bug
        - categories
        - collections
        - comments
        - communities
        - cultural protocols
        - customization
        - dictionary
        - digital heritage
        - integrations
        - local contexts
        - localization
        - mapping and leaflet
        - media
        - migration
        - notifications and events
        - person records
        - publishing workflows
        - roundtrip
        - search and discovery
        - site configuration and administration
        - taxonomies
        - theme/look and feel
        - user management
        - label: other
    validations:
      required: true

  - type: input
    id: story_topic_other
    attributes: 
      label: Other topics
      description: If you selected "Other topics", please briefly describe your story topic.
    validations:
      required: false

  - type: dropdown
    id: user_type
    attributes:
      label: In this user role
      multiple: true
      description: Select each user type that this applies to. Can select multiple user types. 
      options:
        - Mukurtu administrator
        - Community manager
        - Community affiliate
        - Protocol steward
        - Protocol member
        - Protocol affiliate
        - Contributor
        - Community record steward
        - Curator
        - Language steward
        - Lanugage contributor
        - Authenticated user
        - Visitor
    validations:
      required: true

  - type: input
    id: Action
    attributes:
      label: I want to perform this action
      description: Please describe the action you would like to take in this role.
    validations:
      required: true

  - type: input
    id: Benefit
    attributes:
      label: So that this benefit will occur. 
      description: Please describe the benefit that taking this action would confer.
    validations:
      required: true

  - type: input
    id: Acceptance_criteria
    attributes:
      label: Acceptance criteria
      description: A list of items or descriptions of what success looks like for the action or feature described. For a list, please number or bullet your points.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Example screenshots
      description: Optionally attach screenshots here.
      placeholder: If you have an example of something similar from elsewhere, you can add screenshots here. 
  
  - type: input
    id: submitting_org
    attributes: 
      label: Organization
      description: Identify your institution, organization, or community.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Support Tools: 
        - [Mukurtu 4 User Manual](https://mukurtu-user-manual.readthedocs.io/)
