name: GitHub Issue Parser
  # You may pin to the exact commit or the version.
  uses: stefanbuck/github-issue-parser@a2288dcd2cd99cf25f64ff3ef2dbed757c3a53ce
  uses: stefanbuck/github-issue-parser@v3.0.1
  with:
    # Path to the issue form template file
    template-path: # .github/ISSUE_TEMPLATE
    # Issue body to parse
    issue-body: # default is ${{ github.event.issue.body }}

            - name: Advanced Issue Labeler
  # You may pin to the exact commit or the version.
  # uses: redhat-plumbers-in-action/advanced-issue-labeler@0db433d412193574252480b4fc22f2e4319a4ea3
  uses: redhat-plumbers-in-action/advanced-issue-labeler@v3.2.2
  with:
    # Representation of issue form in JSON type
    issue-form: 
    # Each issue form can have defined different labeling policy, this option is used to specify which policy should be used.
    template: # optional, default is 
    # Section of form that is used to determine labels
    section: # optional, default is 
    # Array of words excluded from labeling process, these words won't be set as labels. Use yaml `|` syntax when setting multiple values.
    block-list: # optional, default is 
    # Path to configuration file
    config-path: # default is .github/advanced-issue-labeler.yml
    # GitHub token used to set issue labels
    token: 
name: Issue labeler
on:
  issues:
    types: [ opened ]

permissions:
  contents: read

jobs:
  label-component:
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      issues: write

    steps:
      - uses: actions/checkout@v3

      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/userstoriesgeneral.yml

      - name: Set labels based on story_topic field
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: story_topic
          block-list: |
            None
            Other
          token: ${{ secrets.GITHUB_TOKEN }}
          
